/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego Aristizabal
 * @see Uninpahu
 */
import javax.swing.DefaultListModel;

public class principal extends javax.swing.JFrame {

    int CanNum1;

    /**
     * Creacion de la clase principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista2 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        burbuja = new javax.swing.JButton();
        insercionBinaria = new javax.swing.JButton();
        Shell = new javax.swing.JButton();
        CanNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Seleccion = new javax.swing.JButton();
        burbujaMejorada = new javax.swing.JButton();
        Inserccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lista1);

        jScrollPane2.setViewportView(lista2);

        jLabel1.setText("Desordenado");

        jLabel2.setText("Ordenado");

        burbuja.setText("Burbuja");
        burbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burbujaActionPerformed(evt);
            }
        });

        insercionBinaria.setText("Insercion Binaria");
        insercionBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insercionBinariaActionPerformed(evt);
            }
        });

        Shell.setText("Shell");
        Shell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShellActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de Numeros: ");

        Seleccion.setText("Seleccion");
        Seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionActionPerformed(evt);
            }
        });

        burbujaMejorada.setText("Burbuja Mejorada");
        burbujaMejorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burbujaMejoradaActionPerformed(evt);
            }
        });

        Inserccion.setText("Inserccion");
        Inserccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CanNum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(insercionBinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(Shell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(burbuja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Seleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(burbujaMejorada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inserccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burbuja)
                    .addComponent(Seleccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Shell)
                    .addComponent(burbujaMejorada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insercionBinaria)
                    .addComponent(Inserccion))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CanNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//metodo Burbuja
private void burbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burbujaActionPerformed
// TODO add your handling code here:
    Ordenamientos datos = new Ordenamientos(Integer.parseInt(CanNum.getText()));
    int[] valores;
    int i;
    valores = datos.getNumeros();

    DefaultListModel l1 = new DefaultListModel();
    for (i = 0; i < valores.length; ++i) {
        l1.addElement(valores[i]);
    }
    lista1.setModel(l1);

    valores = datos.Burbuja();

    DefaultListModel l2 = new DefaultListModel();
    for (i = 0; i < valores.length; ++i) {
        l2.addElement(valores[i]);
    }
    lista2.setModel(l2);
}//GEN-LAST:event_burbujaActionPerformed

//Metodo Inserción binaria
private void insercionBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insercionBinariaActionPerformed
// TODO add your handling code here:
    Ordenamientos valores = new Ordenamientos(Integer.parseInt(CanNum.getText()));
    int[] arreglo1 = valores.getNumeros();
    int[] arreglo2 = valores.InsercionBinaria();
    int i;

    DefaultListModel l1 = new DefaultListModel();
    for (i = 0; i < arreglo1.length; ++i) {
        l1.addElement(arreglo1[i]);
    }
    lista1.setModel(l1);

    DefaultListModel l2 = new DefaultListModel();
    for (i = 0; i < arreglo2.length; ++i) {
        l2.addElement(arreglo2[i]);
    }
    lista2.setModel(l2);

}//GEN-LAST:event_insercionBinariaActionPerformed

    //Metodo Shell
    private void ShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShellActionPerformed
        // TODO add your handling code here:
        Ordenamientos datos = new Ordenamientos(Integer.parseInt(CanNum.getText()));
        int[] valores;
        int i;
        valores = datos.getNumeros();

        DefaultListModel l3 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l3.addElement(valores[i]);
        }
        lista1.setModel(l3);

        valores = datos.Shell();

        DefaultListModel l2 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l2.addElement(valores[i]);
        }
        lista2.setModel(l2);

    }//GEN-LAST:event_ShellActionPerformed

    //Metodo Seleccion
    private void SeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionActionPerformed
        Ordenamientos datos = new Ordenamientos(Integer.parseInt(CanNum.getText()));
        int[] valores;
        int i;
        valores = datos.getNumeros();

        DefaultListModel l1 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l1.addElement(valores[i]);
        }
        lista1.setModel(l1);

        valores = datos.Seleccion();

        DefaultListModel l2 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l2.addElement(valores[i]);
        }
        lista2.setModel(l2);        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionActionPerformed

    //Metodo Burbuja Mejorada
    private void burbujaMejoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burbujaMejoradaActionPerformed
        Ordenamientos datos = new Ordenamientos(Integer.parseInt(CanNum.getText()));
        int[] valores;
        int i;
        valores = datos.getNumeros();

        DefaultListModel l1 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l1.addElement(valores[i]);
        }
        lista1.setModel(l1);

        valores = datos.BurbujaMejorada();

        DefaultListModel l2 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l2.addElement(valores[i]);
        }
        lista2.setModel(l2);        // TODO add your handling code here:
    }//GEN-LAST:event_burbujaMejoradaActionPerformed

    //Metodo Inserción
    private void InserccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserccionActionPerformed
        Ordenamientos datos = new Ordenamientos(Integer.parseInt(CanNum.getText()));
        int[] valores;
        int i;
        valores = datos.getNumeros();

        DefaultListModel l1 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l1.addElement(valores[i]);
        }
        lista1.setModel(l1);

        valores = datos.Insercion();

        DefaultListModel l2 = new DefaultListModel();
        for (i = 0; i < valores.length; ++i) {
            l2.addElement(valores[i]);
        }
        lista2.setModel(l2);        // TODO add your handling code here:
    }//GEN-LAST:event_InserccionActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //declaracion de variables de JavaSwing
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CanNum;
    private javax.swing.JButton Inserccion;
    private javax.swing.JButton Seleccion;
    private javax.swing.JButton Shell;
    private javax.swing.JButton burbuja;
    private javax.swing.JButton burbujaMejorada;
    private javax.swing.JButton insercionBinaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lista1;
    private javax.swing.JList lista2;
    // End of variables declaration//GEN-END:variables
}
